### ISSUE TITLE
Report does not show failed tests

### ISSUE THREAD

**Issue by ampc** [hdorgeval/testcafe-starter#5]
When executing `npm run testcafe-static-analyser` the report always show the tests results as passed even when they fail.

static-analyser-report.json
```
  "name": "I should see first and last name",
            "result": {
              "duration": 0,
              "status": "passed"
            },
```

console output:
 ```
1) AssertionError: expected 'Automated Test' to include 'aaa'

      Browser: Chrome 71.0.3578 / Linux 0.0.0

         10 |/**
         11 | * @step
         12 | * @then("I should see first and last name")
         13 | */
         14 |export default async (_: string) => {
       > 15 |  await t.expect(basePage.usermenuName.innerText).contains('aaa');
         16 |};
         17 |
```

**Comment by hdorgeval** [comment]
Hi @ampc, `testcafe-static-analyser` is not a test execution reporter, it is just a source code parser that generates a JSON report and then generates an HTML page from this JSON.

The ambiguity relies on the fact that this tool is based on [multiple-cucumber-html-reporter](https://github.com/wswebcreation/multiple-cucumber-html-reporter) that is a test execution reporter.

If you want to report in HTML, you could try the HTML TestCafe reporter or `testcafe-reporter-cucumber-json`. Tell me if you want me to integrate such a reporter in this starter project.

**Comment by ampc** [comment]
@hdorgeval  I see, I would appreciate if you could integrate `multiple-cucumber-html-reporter` for test execution reports like on this project https://github.com/comsysto/testcafecucumberdemo. It also merges the JSON reports. 
I think this feature would help more people using `testcafe-starter` as a intro to TestCafé. Thank you for your work :+1:  

example:
http://testcafedemo.comsysto.com:8080/job/testcafe-demo/job/master/26/HTML_20Report_5f04_2f11_2f2018_5f23_3a16_3a20/

**Comment by hdorgeval** [comment]
@ampc , thank you for your feedback. I will follow your suggestions. I will let you know when these features will be integrated in he project

**Comment by hdorgeval** [comment]
@ampc , I just release v4.0.0 of testcafe-starter with HTML reporting
